version: "3"
services:
  fortress:
    container_name: "fortress_web"
    build: .
    volumes:
      - .:/home/fortress/src
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Jakarta
      - DEBIAN_FRONTEND=noninteractive
      - FLASK_APP=/home/fortress/src/run.py
      - FLASK_DEBUG=1
      - ENV=devel
    # command: flask run --host=0.0.0.0 --port=8080
